{% set version = "2.2.3" %}

package:
  name: bob.ip.base
  version: {{ version }}

source:
  fn: bob.ip.base-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.ip.base/bob.ip.base-{{ version }}.zip
  md5: ae77494a8f54129c76cdf01107a36d21

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - matplotlib
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.sp
    - bob.io.base
    - bob.math
    - vlfeat 0.9.20
    - boost 1.61.*
    - cmake
    - pkg-config

  run:
    - python
    - matplotlib
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.sp
    - bob.io.base
    - bob.math
    - vlfeat 0.9.20
    - boost 1.61.*

test:
  commands:
    - nosetests -sv bob.ip.base

  imports:
    - bob
    - bob.ip
    - bob.ip.base
    - bob.ip.base.test

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Basic Image Processing Utilities for Bob

extra:
  recipe-maintainers:
    - 183amir
